# Generated by Django 4.0.3 on 2022-04-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Preventative', 'Preventative'), ('Restorative', 'Restorative'), ('Cosmetic', 'Cosmetic')], max_length=30),
        ),
    ]
