# Generated by Django 4.0.3 on 2022-04-03 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_review_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.review'),
            preserve_default=False,
        ),
    ]
