# Generated by Django 4.0.3 on 2022-04-03 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_appointment_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.review'),
        ),
    ]
