# Generated by Django 4.0.3 on 2022-04-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_appointment_review_review_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='appointment',
        ),
    ]
