# Generated by Django 4.0.3 on 2022-04-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_review_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
