# Generated by Django 4.0.3 on 2022-04-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_review_disliked_review_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='disliked',
        ),
        migrations.RemoveField(
            model_name='review',
            name='liked',
        ),
    ]
